### ISSUE TITLE
$77 is showed in windows defender execlude

### ISSUE THREAD

**Issue by SkynetCorporations** [bytecode77/r77-rootkit#102]
hi
$77 is showed in windows defender execlude there is anything to do for hide it ? 
thanks

**Comment by bytecode77** [comment]
That's some Windows Defender internal data structures used to store the exclusion list. I wouldn't hook into that.

* one, because it's fairly specific and will probably change over time
* two, because tampering with AV owned data is not very clever
* and finally, because a feature must be worth it, because every hook introduces potential bugs, performance issues, or in this case, crashes upon breaking changes.

**Comment by SkynetCorporations** [comment]
there is no solution for hide it from windows defender exclude  ?

**Comment by bytecode77** [comment]
If you dig deep & long enough, there sure is a way to hook into this list and exclude hidden entries. However, I won't implement it into the mainstream r77 release. Since it's very specific to your use case, you would need to do your own implementation - or otherwise live without that feature.

**Comment by SkynetCorporations** [comment]
I’m sure in older versions in r77 this features is exist and I don’t know why you delete this features from it !!

**Comment by bytecode77** [comment]
Nope, there is no feature that hides items from the Windows Defender exlcusion list. Otherwise, it would have been documented as feature, followed by a change log entry explaining why it was removed.

Maybe Windows Defender changed how the list was generated, don't know... But anyway, doesn't this all imply that you have full access to the computer, since you can change Windows Defender configuration?

**Comment by SkynetCorporations** [comment]
i try to do it but all try was failed bcs of that i contact you

**Comment by bytecode77** [comment]
You didn't fail... it's important to realize that implementing such a feature very well takes **weeks**, at least. Each and every feature took me days, up to weeks to implement. Finding the right function to hook and implementing the hook correctly is just cumbersome. Even that AMSI bypass, which requires only 5 bytes to be written to memory took me 3 weeks to implement.

But with a lot of reverse engineering skills and patience, anything can be done. But I hope you can now understand better why I won't implement hiding features as per request. Sorry to call you off like that, though.

**Comment by SkynetCorporations** [comment]
void InstallHooks() {

	OriginalNtOpenKeyEx = (NT_NTOPENKEYEX)DetourFindFunction("ntdll.dll", "NtOpenKeyEx");
	DetourAttach((PVOID*)&OriginalNtOpenKeyEx, HookedNtOpenKeyEx);

	OriginalNtSetValueKey = (NT_NTSETVALUEKEY)DetourFindFunction("ntdll.dll", "NtSetValueKey");
	DetourAttach((PVOID*)OriginalNtSetValueKey, HookedNtSetValueKey);
}
typedef NTSTATUS(NTAPI* NT_NTOPENKEYEX)(
	IN HANDLE KeyHandle,
	IN ACCESS_MASK DesiredAccess,
	IN ULONG OpenOptions
	);

typedef NTSTATUS(NTAPI* NT_NTSETVALUEKEY)(
	IN HANDLE KeyHandle,
	IN PUNICODE_STRING ValueName,
	IN ULONG TitleIndex,
	IN ULONG Type,
	IN PVOID Data,
	IN ULONG DataSize
	);


static NT_NTOPENKEYEX OriginalNtOpenKeyEx = NULL;
static NT_NTSETVALUEKEY OriginalNtSetValueKey = NULL;

NTSTATUS NTAPI HookedNtOpenKeyEx(
	PHANDLE KeyHandle,
	ACCESS_MASK DesiredAccess,
	POBJECT_ATTRIBUTES ObjectAttributes,
	ULONG OpenOptions
);

NTSTATUS NTAPI HookedNtSetValueKey(
	HANDLE KeyHandle,
	PUNICODE_STRING ValueName,
	ULONG TitleIndex,
	ULONG Type,
	PVOID Data,
	ULONG DataSize
);
#define STATUS_OBJECT_NAME_NOT_FOUND ((NTSTATUS)0xC0000034L)
#define STATUS_UNSUCCESSFUL ((NTSTATUS)0xC0000001L)


typedef struct _KEY_BASIC_INFORMATION {
	LARGE_INTEGER LastWriteTime;
	ULONG TitleIndex;
	ULONG NameLength;
	WCHAR Name[1];
} KEY_BASIC_INFORMATION, * PKEY_BASIC_INFORMATION;


NTSTATUS NTAPI HookedNtOpenKeyEx(
	PHANDLE KeyHandle,
	ACCESS_MASK DesiredAccess,
	POBJECT_ATTRIBUTES ObjectAttributes,
	ULONG OpenOptions
) {

	return OriginalNtOpenKeyEx(KeyHandle, DesiredAccess, OpenOptions);

}
NTSTATUS NTAPI HookedNtSetValueKey(
	HANDLE KeyHandle,
	PUNICODE_STRING ValueName,
	ULONG TitleIndex,
	ULONG Type,
	PVOID Data,
	ULONG DataSize
) {

	return OriginalNtSetValueKey(KeyHandle, ValueName, TitleIndex, Type, Data, DataSize);
}
