### ISSUE TITLE
A bug In HookedNtQueryDirectoryFile

### ISSUE THREAD

**Issue by wineggdrop** [bytecode77/r77-rootkit#104]
It only occurs in commandline file listing.
Assume a folder with 3 files,a.txt,b.txt and c.txt and they will list on that order.
assume a.txt is set to be hidden,using command dir *.txt,all 3 files will be hidden.
using "dir *.*" works as normal(because the first file return by NtQueryDirectoryFile is . not a.txt)

reason: when NtQueryDirectoryFile with returnSingleEntry is TRUE(explorer or commandline,the first call of NtQueryDirectoryFile always set returnSingleEntry to true,the next call will set it to false) ,and the first file return by NtQueryDirectoryFile is hidden, 
the line if (current == fileInformation) status = STATUS_NO_MORE_FILES; will be called,then no more file shown even there are more files  in the folder.

**Comment by bytecode77** [comment]
You seem to be on to something... First of, thank you for taking the time to analyze the issue upfront. It really helps a lot in fixing bugs.

I'm looking to reproduce the issue first. Can you share more details on how your files look like and how you used your terminal? I wasn't yet able to reproduce it yet.

![image](https://github.com/user-attachments/assets/bb0a961c-680c-4c57-894e-7291395a3ad1)

**Comment by wineggdrop** [comment]
I test again,it happens on windows Server 2012.

https://github.com/user-attachments/assets/63f72190-95f9-485b-804c-36b3fed495f4

check out this recording,I changed the $r77 to $Shadow only

**Comment by bytecode77** [comment]
I don't have Windows Server, but after seeing the icon of your recycycle bin... I tested it on Windows 7 :D And the bug is reproducible.

I'll get back to you once I fixed it.

**Comment by bytecode77** [comment]
That was a quick one! I've released **version 1.5.3**. The bug was that
