### ISSUE TITLE
What are these ip's used for?

### ISSUE THREAD

**Issue by VibeProgramm** [bytecode77/r77-rootkit#106]
What are these ip's used for?

173.194.194.94 
192.168.0.39
20.99.133.109 
20.99.185.48
20.99.186.246 
23.192.210.9 
23.216.81.152

**Comment by bytecode77** [comment]
Anyway, your question is unrelated to the original r77 release. These IP's are probably from some other repository that uses r77 or whetever. You need to ask there.
