### ISSUE TITLE
Won't install on Windows 10

### ISSUE THREAD

**Issue by Dogenymous** [bytecode77/r77-rootkit#12]
Hi, 

I have been clicking on Install for 50th time but it wont still install, can you help me ?

**Comment by GV13057911485** [comment]
hi,

this install is stealthy, looks like nothing responds, but if you check the file "$77-Example“ with the blackhat icon disappeared, then installed it correctly!

**Comment by bytecode77** [comment]
> I have been clicking on Install for 50th time but it wont still install, can you help me ?

Could you please check the Test Console to see, whether r77 is injected into running processes? Also, the file `$77-Example.exe` should become invisible when you refresh Explorer. However, if there is a bug, I need a little more background to reproduce it.

**Comment by bytecode77** [comment]
Closed. Reason: Inactivity, question is not clear.
