### ISSUE TITLE
Compiling project creates large Install.exe file and it causes errors.

### ISSUE THREAD

**Issue by uncidal** [bytecode77/r77-rootkit#14]
Hey, so I downloaded the master branch and tried to compile it (in visual studio right clicking the solution and clicking build solution), under compiling there was no errors, but the Install.exe file is very big (2,178KB), compared to the one I installed from bytecode77.com (311kb).
And whenever I open the Install.exe I compiled I always get Application Errors from other applications saying something like "The instruction at 0x*** referenced memory at 0x***. The memory could not be read." and a lot of applications close, like visual studio, PerfWatson2.exe and my own program if its open (I get these errors both when I run it with RunPE and if I run it from file explorer). (But after those applications have closed and the Errors are done I am pretty sure it does what its supposed to).

The Install.exe I got from bytecode77.com always runs fine, I can run it with your RunPE code in another program with no problems, I can also run it straight from file explorer. Never had any issues with it. But when I compile it myself it is not the same, I don't have a lot of experience using other peoples projects, so there might be something I missed. I didn't change anything, just download it and opened in visual studio and compiled.

**Comment by bytecode77** [comment]
It seems like you are compiling with `Debug` settings. However, r77 only works properly when compiled with `Release`.

![image](https://user-images.githubusercontent.com/34607975/130120374-2247a9c4-3947-4e05-814c-1f344be3c1d9.png)

**Comment by uncidal** [comment]
Yep that fixed it, thanks :)
