### ISSUE TITLE
I want to hide the EXE with the specified name.Where should I edit?

### ISSUE THREAD

**Issue by 1756816846** [bytecode77/r77-rootkit#27]
![image](https://user-images.githubusercontent.com/22480057/155876245-8edf766e-f09a-444c-831b-7222ed9905d8.png)
Can you edit a configuration for me?
exename=calc.exe

**Comment by 1756816846** [comment]
I added the registry and it has been successful.But you can't use uninstall.exe display file

**Comment by 1756816846** [comment]
It's OK. I forgot something

**Comment by bytecode77** [comment]
The [documentation](https://bytecode77.com/downloads/r77%20Rootkit%20Technical%20Documentation.pdf) is always a good starter, section **`2.7 Configuration System`** in particular.

**Comment by ConstantLearner121** [comment]
> I added the registry and it has been successful.But you can't use uninstall.exe displa

did you use: reg add "HKLM\SOFTWARE\$77config\process_names" /v ExecutablePath /t REG_SZ /d "C:\Program Files\Calc\calc.exe" /f   ?
