### ISSUE TITLE
Attacking all files in to one

### ISSUE THREAD

**Issue by Dontmindmes** [bytecode77/r77-rootkit#3]
How can i combine the process tohide, the hider, and the dll in to one file

**Comment by bytecode77** [comment]
The "process to hide" should refer to your main application, i.e. the installed <s>malware</s> ehem.. software.

Your software's job is similar to the provided example executable: Drop the r77 DLL somewhere and inject it into every process, use AppInit_DLLs or both methods. I recommend AppInit_DLLs, and injecting only after initial installation.

The "hider" thereby refers to your software, which drops and installs the DLL.

And to have only one file, you should deploy r77.dll in the resources of your sofware and unpack it upon installation.
