### ISSUE TITLE
how to hide a process using a command line?

### ISSUE THREAD

**Issue by rednas0812** [bytecode77/r77-rootkit#32]
example:

r77rootkit.exe -hide 'processID' or 'process name'

**Comment by bytecode77** [comment]
1. You need to first install the rootkit. For this, just execute `Install.exe`.
2. Wait about 500ms until the registry key `$77config` was created by the rootkit.
3. Write the PID or process name to `HKEY_LOCAL_MACHINE\SOFTWARE\$77config`

This is explained in more detail in the [documentation](https://docs.bytecode77.com/r77-rootkit/Technical%20Documentation.pdf).

![image](https://user-images.githubusercontent.com/34607975/188266755-ba597b17-9f37-4f42-a8be-067bfd3dca5e.png)

**Comment by rednas0812** [comment]
Oke Thank you!
