### ISSUE TITLE
registry problem...

### ISSUE THREAD

**Issue by rednas0812** [bytecode77/r77-rootkit#33]
Hiding a process by process name "under key, process_names" doesn't seem to work for me? how do i hide a process name using the name of the process instead of the pid?

**Comment by bytecode77** [comment]
Did you set it up like this?

Note, that the contents of the value is relevant, but not the name:

![image](https://user-images.githubusercontent.com/34607975/188501684-f19d9d1b-b5bc-4ac4-908f-8c2ed0b28bac.png)

Also, is r77 injected in TaskMgr? Even though r77 is completely fileless, AV vendors do update their detection routines, which can cause r77 to stop working correctly. Can you check the Test Console, whether r77 is properly running? It doesn't need to be installed... If it's injected in TaskMgr.exe, that's enough.

**Comment by rednas0812** [comment]
Hi! It actually worked but somehow the testconsole didn't mark it as hidden but in the taskmanager it was hidden...

thank you very much!

**Comment by bytecode77** [comment]
Glad it works.

The test console actually only shows the hidden-icon when hidden by PID, not when hidden by process name. When you click on that button, the PID is entered in the `$77config` key, not the process name.
