### ISSUE TITLE
How do I communicate with the rootkit?

### ISSUE THREAD

**Issue by WilleLX1** [bytecode77/r77-rootkit#37]
Hello!
This is most likely a simple question, but I desperately need assistance. So I know that the rootkit starts a pipe and that any data I send to it is executed. The only issue here is that I have no idea how or what data I should send. Any assistance would be greatly appreciated.
Regards WilleLX1

**Comment by bytecode77** [comment]
There are several control codes that you can send to the control pipe ([documentation](https://docs.bytecode77.com/r77-rootkit/Technical%20Documentation.pdf) section 3.3 Control Pipe).

For example `CONTROL_USER_SHELLEXEC` or `CONTROL_USER_RUNPE` are useful control codes to execute an EXE file.

There is a [code example in C++](https://github.com/bytecode77/r77-rootkit/blob/master/%24Examples/ControlPipe.cpp) to demonstrate sending a ShellExec control code. Data that you send must be in a specific format that is described in the documentation and that you can get a better grasp on from the example.

Other control codes just have different parameters, but the logic is always the same.

**Comment by WilleLX1** [comment]
Hello again! Thank you for the help, I really appreciate it.

Regards WilleLX1
