### ISSUE TITLE
Recompile r77 with PROCESS_EXCLUSIONS

### ISSUE THREAD

**Issue by joy300loy300** [bytecode77/r77-rootkit#45]
Hi, please tell me how I can compile r77 again with the constants, I need the injections not to affect explorer.exe and bash.exe .
Which programs or commands are needed for compilation and how can I do it in general (step by step, im beginner)?
thank you very much for your help

**Comment by bytecode77** [comment]
You need to install Visual Studio 2022 Community Edition. Then you can open the solution file, select **Release**, not **Debug** mode and **Rebuild Solution**.

**Comment by joy300loy300** [comment]
![image](https://github.com/bytecode77/r77-rootkit/assets/82812042/2d6b08c8-a6f0-48eb-bee7-7a78d4978a80)
![image](https://github.com/bytecode77/r77-rootkit/assets/82812042/524eeb63-38df-42f0-be28-89094c7d3655)
Is this the correct code?

**Comment by bytecode77** [comment]
`GlobalAssemblyInfo` does not need the process exclusion list. The change in `r77def.h` is sufficient.
