### ISSUE TITLE
Changing the prefix

### ISSUE THREAD

**Issue by Sockd08** [bytecode77/r77-rootkit#47]
Where is the prefix located in the code? I want to change the prefix so it hides files that start with ÷77 or smth like that

**Comment by bytecode77** [comment]
In [GlobalAssemblyInfo.cs](https://github.com/bytecode77/r77-rootkit/blob/master/Global/GlobalAssemblyInfo.cs#L12) and [r77def.h](https://github.com/bytecode77/r77-rootkit/blob/master/r77api/r77def.h#L9)

Then recompile the solution and you're done.
