### ISSUE TITLE
Compilation Error - File Not Found

### ISSUE THREAD

**Issue by x0meko** [bytecode77/r77-rootkit#50]
![image](https://github.com/bytecode77/r77-rootkit/assets/94765731/8998fc8c-1142-4add-bfb9-c44d5d6c1675)
Hi, first of all, thanks for the great project - I can't wait to get it all set up so I can dig into it at length.

I seem to be running into an issue when attempting to compile the project - using Visual Studio 2022 with the necessary .NET framework developer package (which I believe was 4.7, Visual Studio stopped giving me import warnings after this so I'm assuming install worked correctly. I'm able to compile the beginning stages of the project (up to this point) but solution fails at Installer stage. 
![image](https://github.com/bytecode77/r77-rootkit/assets/94765731/2d83d099-e104-430c-a47f-70c91b6a007d)

I get a file not found: Resources\Stager.exe (possibly because Stager creation is failing). Upon trying to manually build the Stager project, I get back:
![image](https://github.com/bytecode77/r77-rootkit/assets/94765731/315da598-317a-4293-9365-b5c8e48c5d0f)

I'm hoping I can get some assistance, please feel free to ask me for any additional info if necessary to help you out, I'm sure I'm messing this up somehow since I am a bit of a VS noob :)

**Comment by bytecode77** [comment]
Somehow, an absolute path ended up in the csproj file: `A:\Code\GitHub\r77-rootkit\[...]` that of course only works on my machine...

I have fixed the project file. When you pull the repo, you should be able to compile.
