### ISSUE TITLE
Teaching lessons

### ISSUE THREAD

**Issue by jsk6** [bytecode77/r77-rootkit#64]
Is there any chance i can pay you to teach me this stuff ?
maybe we create a zoom meeting with those who want to join or discord channel, i mean it's up to you

**Comment by Knakiri** [comment]
i dont know what you want to learn but writing entire rootkit is not something to teach in a few minutes.

**Comment by bytecode77** [comment]
I'm self taught and I learned programming 20 years ago, hacking 15 years ago.

Don't get me wrong, but I don't want to steal your money by teaching you only some concrete techniques. What you should do is 1.) become good at writing code & developing software in general. Without this skill, even knowing all these techniques doesn't help you. You still need to be able to put them together correctly. 2.) If you are already a good coder and you're interested in hacking, then you will understand these techniques naturally. Too many people try to become leet hackers without any coding skills. This leaves them with only being able to use existing tools that someone else wrote.

Not sure how deep your general coding skills are so far. But usually someone who's interested much into programming will usually read and aquire information and learn pretty quickly. Good luck ;)

**Comment by jsk6** [comment]
i got your point, self-sufficient is what we are talking about, I made many wonderful GUI apps using qt designer and ending up by coding them ( this helped me in creating a malware of mine that i give it a name with " Grudge ") beside of that i'm currently watching Mr. robot which is a bit sarcastic thing to do but my purpose of it is to know where can hacking path lead me to, so without going into details.. do you have a specific point should i start at ?
![IMG-20231231-WA0012](https://github.com/bytecode77/r77-rootkit/assets/153991843/caee278d-9ca6-4e5a-9c90-63db66b29ff1)
![IMG-20231231-WA0013](https://github.com/bytecode77/r77-rootkit/assets/153991843/5027cdca-c206-43f8-98fe-c2cc0e129dfa)
![IMG-20231231-WA0014](https://github.com/bytecode77/r77-rootkit/assets/153991843/c348ae1d-110c-4940-949a-9085beaaddfd)
![IMG-20231231-WA0015](https://github.com/bytecode77/r77-rootkit/assets/153991843/abe95f85-fe7e-42a5-972c-1503d1212d21)
![IMG-20231231-WA0016](https://github.com/bytecode77/r77-rootkit/assets/153991843/7b941559-d450-477b-ac45-4357c77e2b8b)

**Comment by bytecode77** [comment]
Ah, I see that you are working on some projects there. That is already good, because too many people have no coding skills whatsoever and try to learn hacking ;)

You could try to write a crypter. That way you will have to figure out some in-memory execution and AV evasion. Or you can simply fiddle around with techniques, such as RunPE, living off the land, etc. Techniques like these are always the cornerstone to create something such as a rootkit.

**Comment by jsk6** [comment]
well, i understand now, " successful man " is nothing but an expert loser, I will go through hard things and make many mistakes in order to achieve this.. for now I'm learning C to create an injectable dll file to hide my process from task manager and then i will be learned the first step of rootkit which is " user-mode rootkit ".      (happy new year)
Grudge Malware ( that was the first one of all GUI i have built 1y ago ):
![IMG-20231231-WA0012](https://github.com/bytecode77/r77-rootkit/assets/153991843/afeef0d8-3205-48c4-aa72-5a0516876a75)
![IMG-20231231-WA0013](https://github.com/bytecode77/r77-rootkit/assets/153991843/2b193558-1ec8-449b-823e-5aab3a00b08d)
![IMG-20231231-WA0014](https://github.com/bytecode77/r77-rootkit/assets/153991843/5207f667-8d61-473a-890a-ad0c32b85f81)
![IMG-20231231-WA0015](https://github.com/bytecode77/r77-rootkit/assets/153991843/0e65c115-012b-4c91-b558-b130905bbf68)
