### ISSUE TITLE
"MSB3073"  Error

### ISSUE THREAD

**Issue by jsk6** [bytecode77/r77-rootkit#66]
I don't know but maybe I haven't installed the exact workloads or individual components or some other reason, Here is the Error:

![Error1](https://github.com/bytecode77/r77-rootkit/assets/153991843/e3872509-bf6d-44ea-9012-2cb6aa120d4d)
![Error2](https://github.com/bytecode77/r77-rootkit/assets/153991843/5ab6892a-b235-45ab-8940-0d8d49b5c678)

**Comment by jsk6** [comment]
still the same error, And yea i built it in release mode
![image](https://github.com/bytecode77/r77-rootkit/assets/153991843/03ce3649-9dae-40a6-b3a1-2b63b39adf13)

**Comment by bytecode77** [comment]
Could you copy the error message and try to execute these commands manually, to see which one failed and why? If you do this, I could solve the issue much faster, otherwise it's a little bit of a guessing game...

Also, do you have AV running that might block the build process?

**Comment by jsk6** [comment]
yep, it happened because of my AV " Problem Solved! "
