### ISSUE TITLE
testconsole won't work

### ISSUE THREAD

**Issue by MaggieKong** [bytecode77/r77-rootkit#73]
I download the latest source code and try to compile it with Microsoft Visual Studio Enterprise 2022,installer and uninstaller works fine,but testconsole.exe works on windows 10 but fail to run on Windows Server 2012 and Server 2016.

![image](https://github.com/bytecode77/r77-rootkit/assets/164617506/c3fdf732-34ba-43fc-bb9f-1f33cba597b8)
I got this error on Windows server 2012

Server 2016 just won't show up the testconsole gui.

**Comment by bytecode77** [comment]
That's strange. Is there any detail on the error, such as in the EventViewer? Is the .NET 4 runtime installed? If so, is only the .NET 4 client profile installed, or the full .NET 4.x runtime?

Note that you really only need to install the .NET runtime for the Test Console. The rootkit itself works with whatever ships with the operating system and there is no need to install anything.

**Comment by MaggieKong** [comment]
Windows Server 2012 
![image](https://github.com/bytecode77/r77-rootkit/assets/164617506/526b01d2-56bf-459d-aeb6-aaba9cc41efb)
![image](https://github.com/bytecode77/r77-rootkit/assets/164617506/4016762a-785b-4e34-9baa-106e5e33a305)

And Windows Server 2016 is the same .net framework installed

**Comment by bytecode77** [comment]
One important question first: Is the rootkit running properly, though? I'm asking because I never tested on Windows Server.

As for the Test Console. That one requires .NET 4.7. Is this version installed? And is there any chance you could install Visual Studio on Windows Server to actually debug the Test Console to see where the error occurrs?

**Comment by MaggieKong** [comment]
1.Rootkit works perfectly on both server
2..NET 4.8X is installed but not .NET 4.7(I will try to install .NET 4.7 and test again)

**Comment by bytecode77** [comment]
No problem. At least I now know that r77 works on Windows Server ;)
