### ISSUE TITLE
file not found: Resources\Stager.exe	

### ISSUE THREAD

**Issue by error0x1337** [bytecode77/r77-rootkit#92]

**Comment by bytecode77** [comment]
The more description, the faster your problem will be solved...

The target framework of Stager.csproj is set to .NET 3.5 for reasons described in the documentation. You probably need to install that framework version.

**Comment by error0x1337** [comment]
> The more description, the faster your problem will be solved...
> 
> The target framework of Stager.csproj is set to .NET 3.5 for reasons described in the documentation. You probably need to install that framework version.

Thanks ill try that.
 
I've one more question, If the rootkit hides the registry $77-configuration from which we have to hide the editable, how to write the config programmatically?

**Comment by error0x1337** [comment]
@bytecode77 
I installed the service, it was working fine. but after reboot its fucked up. when i open the testconsole it said "r77 service is not running"

**Comment by bytecode77** [comment]
> I've one more question, If the rootkit hides the registry $77-configuration from which we have to hide the executable, how to write to the config programmatically to set keys?

The registry key will not appear, but you can still open it and write to it, even without elevated privileges. There are other ways, too, to hide an executable (see the documentation)

**Comment by error0x1337** [comment]
> > I've one more question, If the rootkit hides the registry $77-configuration from which we have to hide the executable, how to write to the config programmatically to set keys?
> 
> The registry key will not appear, but you can still open it and write to it, even without elevated privileges. There are other ways, too, to hide an executable (see the documentation)

Bro, it broked my vm after reboot.

**Comment by error0x1337** [comment]
i added simple c++ application to the startup but it didnt started why?

**Comment by bytecode77** [comment]
Is your simple C++ app a GUI app, like a MessageBox? If so, then you should know that startup applications start under the SYSTEM user, which doesn't have a desktop. Was that the case?

Have you read the documentation yet to spot potential usage errors?

**Comment by error0x1337** [comment]
and how to start the hidden file ? i cant start it programmatically or from cmd

**Comment by bytecode77** [comment]
> and how to start the hidden file ? i cant start it programmatically or from cmd

I'm not sure where you're at... If you are talking about startup programs, see the documentation for how to configure the `$77config\startup` key.

To launch a file programmatically that is hidden, you can use the control pipe.

Please help me to help you by asking specific, detailed and elaborated questions.

**Comment by bytecode77** [comment]
> will it cause any problems like BSOD, or will it no longer be persistent like before?

Excluding these particualr processes will just make hidden stuff more visible, because some processes then can see it. I wouldn't exclude all services (svchost). Crashes should usually never happen, though.
