### ISSUE TITLE
File.Exists or Directory.Exists still return true

### ISSUE THREAD

**Issue by mrapxs** [bytecode77/r77-rootkit#98]
Doing File.Exists or Directory.Exists any created r77 folder under x64 or x86 results in True if the folder does exist, regardless of injection.

**Comment by bytecode77** [comment]
They return true as by design. r77 hides files and directories from directory lists, however, if you **know** the name of the file, you can open it. r77 assumes that only you know the name of the hidden file, which makes maintenance easier.
